language: java
dist: trust
#sudo: false
#install: true
#jdk:
#  - oraclejdk8

addons:
  sonarcloud:
    organization: "dieppa-github"
    token:
      secure: S3cVfpP41UQ2M9vhc5E36TiIZZxJVm5bxbATFAHtugKWJJEGJOJ7rRpE27nWu06XLhD3mdTkS28uVkbw6FldRWMH2sGMkqpE9uMFz5DLgJt27s0GSoyxD9ptCdnrQf91b/ZcGhz9jte6ahfoSEND5Q3sD544gsUMmTGyZIqVlDV79zJ2vdSWBvpEJ+ljw7a4wTIJmgs9IHSoxwtgSb1VmjfbFTW703FLXTbA2JhRDC/h37owcCBsgQHIvhBZSU9T8eDD9oim9QW9uqDzojFRmYow1UV0yfPIjPjkkT10o0gg9PAwwah5QshGXRJZkFNj+V7KEcOikFquAUqAIq0K/Uqzar6eeR3e3Gi42wwWco4nQNgbxB6kTiXjwDlcB0qNLdjBm8zUDLVdBTxfm5D2y8byVsWGuTbdSlM2hXLFpoRG9JaeFUwQR2OLpVBwXbPXYAxGLAMbzHqEuIza77jXtXQ0v7XIpOAtpkULQH+fzDP8R49byyud0V4RgB9yq1GyoA6fte4fkBbYlN/uOe/ZkkzLRLQfhoTZPozCzYdTSg2/XsVeOZIHsJMMtREdTkUuPjjALZ8aAiSHXOQpNzRZcYzIQX2KJJqY81uvO32TQ4+X7tRCcR5V1DgCghd7v6+hADovMgj+BSBEnNHQttbqmx3Kvw93FZAxQ6g0+mO9DTI=

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Psonarqube -Dmaven.test.failure.ignore=true -Dsonar.analysis.mode=preview -Dsonar.github.pullRequest=3 -Dsonar.github.repository=cloudyrock/mongock -Dsonar.github.oauth=4f5b5f35c9454216f0b3241867b2de92840e4215 -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=dieppa-github -Dsonar.login=b399a4341c829aa96ec3a1c164ca1db1dc0e8e0d

#cache:
#  directories:
#    - '$HOME/.m2/repository'
#    - '$HOME/.sonar/cache'